/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBegreberRouteImport } from './routes/_authenticated/begreber'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKalenderRouteImport } from './routes/_authenticated/kalender'
import { Route as AuthenticatedRepetitionRouteImport } from './routes/_authenticated/repetition'
import { Route as ApiKalenderRouteImport } from './routes/api/kalender'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedFagFagIdRouteImport } from './routes/_authenticated/fag.$fagId'
import { Route as ApiFagFagNavnForelaesningerRouteImport } from './routes/api/fag/$fagNavn/forelaesninger'
import { Route as AuthenticatedFagFagIdNoterForelaesningIdRouteImport } from './routes/_authenticated/fag.$fagId_.noter.$forelaesningId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBegreberRoute = AuthenticatedBegreberRouteImport.update({
  id: '/begreber',
  path: '/begreber',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalenderRoute = AuthenticatedKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepetitionRoute = AuthenticatedRepetitionRouteImport.update({
  id: '/repetition',
  path: '/repetition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiKalenderRoute = ApiKalenderRouteImport.update({
  id: '/api/kalender',
  path: '/api/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFagFagIdRoute = AuthenticatedFagFagIdRouteImport.update({
  id: '/fag/$fagId',
  path: '/fag/$fagId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiFagFagNavnForelaesningerRoute =
  ApiFagFagNavnForelaesningerRouteImport.update({
    id: '/api/fag/$fagNavn/forelaesninger',
    path: '/api/fag/$fagNavn/forelaesninger',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFagFagIdNoterForelaesningIdRoute =
  AuthenticatedFagFagIdNoterForelaesningIdRouteImport.update({
    id: '/fag/$fagId_/noter/$forelaesningId',
    path: '/fag/$fagId/noter/$forelaesningId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/begreber': typeof AuthenticatedBegreberRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/repetition': typeof AuthenticatedRepetitionRoute
  '/api/kalender': typeof ApiKalenderRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/fag/$fagId': typeof AuthenticatedFagFagIdRoute
  '/api/fag/$fagNavn/forelaesninger': typeof ApiFagFagNavnForelaesningerRoute
  '/fag/$fagId/noter/$forelaesningId': typeof AuthenticatedFagFagIdNoterForelaesningIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/begreber': typeof AuthenticatedBegreberRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kalender': typeof AuthenticatedKalenderRoute
  '/repetition': typeof AuthenticatedRepetitionRoute
  '/api/kalender': typeof ApiKalenderRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/fag/$fagId': typeof AuthenticatedFagFagIdRoute
  '/api/fag/$fagNavn/forelaesninger': typeof ApiFagFagNavnForelaesningerRoute
  '/fag/$fagId/noter/$forelaesningId': typeof AuthenticatedFagFagIdNoterForelaesningIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/begreber': typeof AuthenticatedBegreberRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kalender': typeof AuthenticatedKalenderRoute
  '/_authenticated/repetition': typeof AuthenticatedRepetitionRoute
  '/api/kalender': typeof ApiKalenderRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/fag/$fagId': typeof AuthenticatedFagFagIdRoute
  '/api/fag/$fagNavn/forelaesninger': typeof ApiFagFagNavnForelaesningerRoute
  '/_authenticated/fag/$fagId_/noter/$forelaesningId': typeof AuthenticatedFagFagIdNoterForelaesningIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/begreber'
    | '/dashboard'
    | '/kalender'
    | '/repetition'
    | '/api/kalender'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/fag/$fagId'
    | '/api/fag/$fagNavn/forelaesninger'
    | '/fag/$fagId/noter/$forelaesningId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/begreber'
    | '/dashboard'
    | '/kalender'
    | '/repetition'
    | '/api/kalender'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/fag/$fagId'
    | '/api/fag/$fagNavn/forelaesninger'
    | '/fag/$fagId/noter/$forelaesningId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/begreber'
    | '/_authenticated/dashboard'
    | '/_authenticated/kalender'
    | '/_authenticated/repetition'
    | '/api/kalender'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/fag/$fagId'
    | '/api/fag/$fagNavn/forelaesninger'
    | '/_authenticated/fag/$fagId_/noter/$forelaesningId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiKalenderRoute: typeof ApiKalenderRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiFagFagNavnForelaesningerRoute: typeof ApiFagFagNavnForelaesningerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/begreber': {
      id: '/_authenticated/begreber'
      path: '/begreber'
      fullPath: '/begreber'
      preLoaderRoute: typeof AuthenticatedBegreberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalender': {
      id: '/_authenticated/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AuthenticatedKalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repetition': {
      id: '/_authenticated/repetition'
      path: '/repetition'
      fullPath: '/repetition'
      preLoaderRoute: typeof AuthenticatedRepetitionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/kalender': {
      id: '/api/kalender'
      path: '/api/kalender'
      fullPath: '/api/kalender'
      preLoaderRoute: typeof ApiKalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fag/$fagId': {
      id: '/_authenticated/fag/$fagId'
      path: '/fag/$fagId'
      fullPath: '/fag/$fagId'
      preLoaderRoute: typeof AuthenticatedFagFagIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/fag/$fagNavn/forelaesninger': {
      id: '/api/fag/$fagNavn/forelaesninger'
      path: '/api/fag/$fagNavn/forelaesninger'
      fullPath: '/api/fag/$fagNavn/forelaesninger'
      preLoaderRoute: typeof ApiFagFagNavnForelaesningerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fag/$fagId_/noter/$forelaesningId': {
      id: '/_authenticated/fag/$fagId_/noter/$forelaesningId'
      path: '/fag/$fagId/noter/$forelaesningId'
      fullPath: '/fag/$fagId/noter/$forelaesningId'
      preLoaderRoute: typeof AuthenticatedFagFagIdNoterForelaesningIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBegreberRoute: typeof AuthenticatedBegreberRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKalenderRoute: typeof AuthenticatedKalenderRoute
  AuthenticatedRepetitionRoute: typeof AuthenticatedRepetitionRoute
  AuthenticatedFagFagIdRoute: typeof AuthenticatedFagFagIdRoute
  AuthenticatedFagFagIdNoterForelaesningIdRoute: typeof AuthenticatedFagFagIdNoterForelaesningIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBegreberRoute: AuthenticatedBegreberRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKalenderRoute: AuthenticatedKalenderRoute,
  AuthenticatedRepetitionRoute: AuthenticatedRepetitionRoute,
  AuthenticatedFagFagIdRoute: AuthenticatedFagFagIdRoute,
  AuthenticatedFagFagIdNoterForelaesningIdRoute:
    AuthenticatedFagFagIdNoterForelaesningIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiKalenderRoute: ApiKalenderRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiFagFagNavnForelaesningerRoute: ApiFagFagNavnForelaesningerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
